name = "math135"
version = "0.1.0"
defaultTargets = ["math135"]

[[lean_lib]]
name = "Math135"

[[lean_exe]]
name = "math135"
root = "Main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
